# Velocity scale
Parfile.ins_inflowVelScale = 1.0

# Restart, checkpoint, and plotting options
Parfile.nend = 10000000
Parfile.tmax = 100.0
Parfile.restart = ".true."
Parfile.checkpointFileNumber = 0
Parfile.checkpointFileIntervalTime = 5.0
Parfile.plotFileNumber = 0
Parfile.plotFileIntervalTime = 1.0
