# Heater name and number of heaters
Heater.name = "pool_boiling"
Heater.dim = 1

# Heater dimensions
Heater.xmin = -2.0
Heater.xmax = 2.0
Heater.zmin = -2.0
Heater.zmax = 2.0
Heater.ymin = 0.0
Heater.ymax = 1e-13

# Wall temperature
Heater.wallTemp = 1.0

# Contact angle information
Heater.advAngle = 45.0
Heater.rcdAngle = 45.0
Heater.velContact = 0.2
Heater.nucWaitTime = 0.4

# Site information
Heater.numSites = 1
Heater.nucSeedRadius = 0.15

# Inverse of Reynolds Number
Parfile.ins_invReynolds = 0.0033

# 1/Fr**2, Fr (Froude Number)
Parfile.ins_gravY = -1.0

# Gas density and viscosity scaled by liquid
Parfile.mph_rhoGas = 0.0049
Parfile.mph_muGas = 0.02
Parfile.mph_iPropSmear = 1.5

# Gas thermal conductivity and specific heat
Parfile.mph_thcoGas = 0.143
Parfile.mph_CpGas = 0.735

# Stefan number and saturation temperature
Parfile.mph_Stefan = 0.16
Parfile.mph_Tsat = 0.0

# Inverse Weber Number
Parfile.mph_invWeber = 1.0

# Prandtl number
Parfile.ht_Prandtl = 7

# Outlet parameters
Parfile.sim_outletSink = -1.0  # Outlet level set sink
Parfile.sim_outletBuffer = 1.0  # Outlet buffer region
Parfile.sim_heaterShowInfo = ".FALSE."

#       Grid dimensionality and geometry
Parfile.geometry = "cartesian"

#       Size of computational volume
Parfile.xmin = 0.0
Parfile.xmax = 2.0
Parfile.ymin = 0.0
Parfile.ymax = 6.0
Parfile.zmin = 0.0
Parfile.zmax = 2.0

#       Boundary conditions
Parfile.xl_boundary_type = "slip_ins"
Parfile.xr_boundary_type = "noslip_ins"
Parfile.yl_boundary_type = "noslip_ins"
Parfile.yr_boundary_type = "outflow_ins"
Parfile.zl_boundary_type = "slip_ins"
Parfile.zr_boundary_type = "noslip_ins"

#       Simulation (grid, time, I/O) parameters
Parfile.run_comment = "Pool Boiling problem"
Parfile.log_file = "INS_Pool_Boiling.log"
Parfile.basenm = "INS_Pool_Boiling_"
Parfile.restart = ".false."
Parfile.nend = 10000000
Parfile.tmax = 10
Parfile.ins_cflFlg = 0
Parfile.ins_cfl = 0.05
Parfile.ins_sigma = 0.05
Parfile.ins_dtSpec = 1.0e-4
Parfile.dtinit = 1.0e-4
Parfile.dtmax = 1.0e-4
Parfile.tstep_change_factor = 1.01
Parfile.ins_pressureCorrect = ".false."

# Integration Scheme:
Parfile.ins_intSchm = 2

Parfile.plot_var_1 = "pres"
Parfile.plot_var_2 = "velx"
Parfile.plot_var_3 = "vely"
Parfile.plot_var_4 = "dfun"
Parfile.plot_var_5 = "temp"
Parfile.plot_var_8 = "mflx"
Parfile.plot_var_9 = "rhoc"
Parfile.plot_var_10 = "curv"
Parfile.plot_var_11 = "nrmx"
Parfile.plot_var_12 = "nrmy"
Parfile.plot_var_13 = "omgm"

Parfile.checkpointFileNumber = 0
Parfile.checkpointFileIntervalTime = 5.0

Parfile.plotFileNumber = 0
Parfile.plotFileIntervalTime = 0.5

Parfile.ignoreForcedPlot = ".TRUE."

# AMR parameters
Parfile.nblockx = 6
Parfile.nblocky = 18
Parfile.nblockz = 6

# Input file to set runtime parameters

# Set highest number for update
# refinement step since in pseudo UG mode
Parfile.nrefs = 10000000

# lrefine min/max since in UG mode
Parfile.lrefine_min = 1
Parfile.lrefine_max = 1

# Flux Conservation for AMR
Parfile.flux_correct = ".true."

# AMReX Poisson Solver Parameters
Parfile.gr_amrexMG_composite_solve = ".TRUE."
Parfile.gr_amrexMG_Tol = 3e-12  # use tol for production runs 1e-13
Parfile.gr_amrexMG_max_iter = 200

# Paramesh parameters
Parfile.gr_pmRpDivergenceFree = 1
Parfile.gr_pmRpNfieldDivf = 2
Parfile.gr_pmRpConsvFluxes = ".TRUE."
Parfile.gr_pmRpConsvFluxDensities = ".FALSE."

# Settings for guard cell filling
Parfile.gr_bcEnableApplyMixedGds = ".FALSE."
Parfile.convertToConsvdForMeshCalls = ".FALSE."
Parfile.convertToConsvdInMeshInterp = ".FALSE."
Parfile.enableMaskedGCFill = ".FALSE."

# HYPRE Poisson Solver Parameters
Parfile.gr_hyprePrintSolveInfo = ".FALSE."
Parfile.gr_hyprePcType = "HYPRE_AMG"
Parfile.gr_hypreSolverType = "HYPRE_BICGSTAB"
Parfile.gr_hypreRelTol = 1.0e-12
Parfile.gr_hypreFloor = 1.0e-16
