# 	Runtime parameters for the Counter Flow problem.
Parfile.gr_pmRpDivergenceFree = 1
Parfile.gr_pmRpNfieldDivf = 2
Parfile.gr_pmRpConsvFluxes = ".TRUE."
Parfile.gr_pmRpConsvFluxDensities = ".FALSE."

# Settings for guard cell filling
Parfile.gr_bcEnableApplyMixedGds = ".FALSE."
Parfile.convertToConsvdForMeshCalls = ".FALSE."
Parfile.convertToConsvdInMeshInterp = ".FALSE."
Parfile.enableMaskedGCFill = ".FALSE."

# Inverse of Reynolds Number
Parfile.ins_invReynolds = 0.005

# 1/Fr**2, Fr (Froude Number)
Parfile.ins_gravY = 0.01

# Gas density and viscosity scaled by liquid
Parfile.mph_rhoGas = 0.001
Parfile.mph_muGas = 0.02
Parfile.mph_iPropSmear = 1.5

# Inverse Weber Number
Parfile.mph_invWeber = 0.004

#       Grid dimensionality and geometry
Parfile.geometry = "cartesian"

# Simulation parameters
Parfile.sim_outletBuffer = 1.0
Parfile.sim_channelDepth = 1.0
Parfile.sim_nozzleFreq = 0.2
Parfile.sim_nozzleAmp = 0.5
Parfile.sim_liqFlowRate = 1.0
Parfile.sim_gasFlowRate = -1.0

#       Size of computational volume
Parfile.xmin = -5.0
Parfile.xmax = 5.0
Parfile.ymin = 0.0
Parfile.ymax = 20.0
Parfile.zmin = -5.0
Parfile.zmax = 5.0

#       Boundary conditions
Parfile.xl_boundary_type = "noslip_ins"
Parfile.xr_boundary_type = "noslip_ins"
Parfile.yl_boundary_type = "inflow_ins"
Parfile.yr_boundary_type = "outflow_ins"
Parfile.zl_boundary_type = "noslip_ins"
Parfile.zr_boundary_type = "noslip_ins"

#       Simulation (grid, time, I/O) parameters
Parfile.run_comment = "Counter Flow problem"
Parfile.log_file = "INS_Counter_Flow.log"
Parfile.basenm = "INS_Counter_Flow_"
Parfile.restart = ".false."
Parfile.nend = 10000000
Parfile.tmax = 70.0
Parfile.ins_cflFlg = 1
Parfile.ins_cfl = 0.05
Parfile.ins_sigma = 0.05
Parfile.ins_dtSpec = 0.1e-3
Parfile.dtinit = 0.1e-3
Parfile.tstep_change_factor = 1.0
ins_pressureCorrect = ".false."

# Integration Scheme:
Parfile.ins_intSchm = 2

Parfile.plot_var_1 = "pres"
Parfile.plot_var_2 = "velx"
Parfile.plot_var_3 = "vely"
Parfile.plot_var_4 = "dfun"
Parfile.plot_var_5 = "dust"
Parfile.plot_var_6 = "omgm"

Parfile.checkpointFileNumber = 0
Parfile.checkpointFileIntervalTime = 5.0

Parfile.plotFileNumber = 0
Parfile.plotFileIntervalTime = 0.1
Parfile.ignoreForcedPlot = ".TRUE."

# AMR parameters
Parfile.nblockx = 10
Parfile.nblocky = 20
Parfile.nblockz = 10
Parfile.nfres = 10000000

Parfile.lrefine_min = 1
Parfile.lrefine_max = 1

# 	Flux Conservation for AMR
Parfile.flux_correct = ".true."

# AMReX Poisson Solver Parameters
Parfile.gr_amrexMG_composite_solve = ".TRUE."
Parfile.gr_amrexMG_Tol = 1e-13
Parfile.gr_amrexMG_max_iter = 1000

# HYPRE Poisson Solver Parameters
Parfile.gr_hyprePrintSolveInfo = ".FALSE."
Parfile.gr_hyprePcType = "HYPRE_AMG"
Parfile.gr_hypreSolverType = "HYPRE_BICGSTAB"
Parfile.gr_hypreRelTol = 1.0e-12
Parfile.gr_hypreFloor = 1.0e-16
