# Number of nucleation sites
Heater.numSites = 200

# Stefan number
Parfile.mph_Stefan = 0.0579

# Restart, checkpoint, and plotting options
Parfile.nend = 10000000
Parfile.tmax = 100.0
Parfile.restart = ".false."
Parfile.checkpointFileNumber = 0
Parfile.checkpointFileIntervalTime = 5.0
Parfile.plotFileNumber = 0
Parfile.plotFileIntervalTime = 1.0
