#       Grid dimensionality and geometry
Parfile.geometry = "cartesian"

# level set iterations
Parfile.ib_lsIt = 3
Parfile.ib_enableSelectiveMapping = ".FALSE."
Parfile.ib_numBodies = 1
Parfile.ib_bodyName = "disk"
Parfile.ib_annQueries = 3
Parfile.ib_bruteForceMapping = ".FALSE."

#       Size of computational volume
Parfile.xmin = -2.0
Parfile.xmax = 2.0
Parfile.ymin = -3.0
Parfile.ymax = 3.0
Parfile.zmin = -2.0
Parfile.zmax = 2.0

Parfile.xl_boundary_type = "user-defined"
Parfile.xr_boundary_type = "user-defined"
Parfile.yl_boundary_type = "user-defined"
Parfile.yr_boundary_type = "user-defined"
Parfile.zl_boundary_type = "user-defined"
Parfile.zr_boundary_type = "user-defined"

#       Simulation (grid, time, I/O) parameters
Parfile.run_comment = "ImBound Unit Test"
Parfile.log_file = "flash.log"
Parfile.basenm = "flash_"
Parfile.restart = ".false."
Parfile.nend = 400
Parfile.tmax = 5.0
Parfile.ins_cflFlg = 0
Parfile.ins_cfl = 0.3
Parfile.ins_sigma = 0.2
Parfile.ins_dtSpec = 1.0e-2
Parfile.dtinit = 1.0e-2
Parfile.tstep_change_factor = 1.0
Parfile.ins_pressureCorrect = ".false."

Parfile.plot_var_1 = "lmda"
Parfile.plot_var_2 = "nmlx"
Parfile.plot_var_3 = "nmly"

Parfile.checkpointFileIntervalTime = 1.0
Parfile.checkpointFileIntervalStep = 5

Parfile.plotFileIntervalTime = 1.0
Parfile.plotFileIntervalStep = 5

# AMR parameters
Parfile.nblockx = 8
Parfile.nblocky = 12
Parfile.nblockz = 8

Parfile.lrefine_min = 1
Parfile.lrefine_max = 5

Parfile.refine_var_count = 1
Parfile.refine_var_1 = "lmda"
Parfile.refine_cutoff_1 = 0.0e0
Parfile.derefine_cutoff_1 = -0.01e0
